image:
  file: .gitpod.Dockerfile

ports:
  # IHP Server
  - port: 8000
    onOpen: open-browser
    visibility: public
  # IDE
  - port: 8001
    onOpen: open-browser

tasks:
  - before: nix-env -iA nixpkgs.mailhog
    command: MailHog

  - init: >
      ( if [ ! -e "Main.hs" ]; then git init; git remote add ihp https://github.com/Gizra/ihp-simple-seat-reservation.git; git pull ihp main --rebase; nix-shell -j auto --cores 0 --quiet --run 'make -s all .envrc; new-application Web'; fi) && nix-shell -j auto --cores 0 --run 'make -s all .envrc' && direnv allow
    command: >
      export IHP_BASEURL=`gp url 8000`;
      export IHP_IDE_BASEURL=`gp url 8001`;
      # Compile CSS
      make -B .envrc
      npm install
      make static/prod.css
      # Start app
      ./start

vscode:
  extensions:
    - haskell.haskell
    - s0kil.vscode-hsx
    - arrterian.nix-env-selector


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true